# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=42)),
                ('last_name', models.CharField(max_length=42)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('university', models.CharField(choices=[('UCAMP', 'Unicamp'), ('USPSP', 'USP - São Paulo'), ('USPSC', 'USP - São Carlos'), ('USPRB', 'USP - Ribeirão'), ('UFSCA', 'UFSCAR'), ('OUTRA', 'Outra')], max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
