# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registree',
            name='chimp_id',
            field=models.CharField(default='', max_length=42),
        ),
    ]
