# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_registree_chimp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registree',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='registree',
            name='last_name',
        ),
        migrations.AddField(
            model_name='registree',
            name='name',
            field=models.CharField(default='', max_length=84),
        ),
    ]
