# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20170123_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='registree',
            name='other',
            field=models.CharField(default='', max_length=42),
        ),
    ]
