# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20170124_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='registree',
            name='status',
            field=models.CharField(default='pending', max_length=42),
        ),
    ]
