# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_registree_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='registree',
            name='referee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='references', to='registration.Registree'),
        ),
        migrations.AlterField(
            model_name='registree',
            name='university',
            field=models.CharField(choices=[('UCAMP', 'Unicamp'), ('USPSP', 'USP - São Paulo'), ('USPSC', 'USP - São Carlos'), ('UFSCA', 'UFSCAR'), ('OUTRA', 'Outra')], max_length=5),
        ),
    ]
